CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,          
    name VARCHAR(255) NOT NULL,     
    campaign VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    dispatched_at TIMESTAMP WITH TIME ZONE DEFAULT NULL   
);